stages:
  - test
  - build
  - test2
  - dev
  - stage
  - prod

install_env:
  stage: test
  script:
    - echo " test 1 --------------------"

run_tests:
  stage: test
  script: 
    - echo " test 2 --------------------"

lintesr:
  stage: test
  script:
    - echo " test linter ------------------"

build:
  stage: build
  script:
    - ./build.sh
  when: manual

tests_after_build:
  stage: test2
  script:
    - echo " test after build 1 --------------------"

deploy dev:
  stage: dev
  script:
    - echo 'running ./build.sh'
  when: manual
  only:
    refs:
      - tags
      - master
      - /^release.*$

deploy stage:
  stage: stage
  script:
    - echo 'running ./build.sh'
  when: manual
  only:
    refs:
      - tags
      - master
      - /^release.*$

deploy prod:
  stage: prod
  script:
    - echo 'running ./build.sh'
  when: manual
  only:
    refs:
      - tags
      - master
